### ISSUE TITLE
Leaves in fertilizer class description

### ISSUE THREAD

**Issue by mowong** [heckman/SimPlant#17]
Let's take out the status "The leaves are so healthy!", in the fertilizer class, and just have descriptors of leaf colors, instead. I've had both "leaves are drooping" and "leaves are so healthy!" at the same time, when I've under watered the plant but fertilizer levels are fine. Getting both comments together is confusing.

**Comment by heckman** [comment]
also there is no limit to the "zones" we can have. we can have a dozen different zones with different status messages... just saying the implementation is the easy part.
