### ISSUE TITLE
Plant doesn't die from lack of water

### ISSUE THREAD

**Issue by mowong** [heckman/SimPlant#5]
I've changed the game logic so now it reads
```
public void step() {
    level -= DECREMENT + DECREMENT_SD * random.nextGaussian();
    if ( level < 0 ) level = **-1;** // > -1 and <= 0 is dead
   // used to read 0, it would never die from lack of water
```
Opening this in issues, want to use this to test GitHub for issue tracking.

**Comment by heckman** [comment]
Fixed this yesterday. The problem wasn't that it didn't go to -1, the problem was that when checking levels, it used a ">=" when it should have been a ">". This error did not occur in the FeedTracker, because it used a ">". I have since changed the WaterTracker in the Master Branch.
